version: '3.8'

services:
  web_statis:
    image: ${DOCKERHUB_USERNAME}/uas-web-statis:latest
    container_name: app_web_statis
    ports:
      - "80:80"
    restart: always

  web_dinamis:
    image: ${DOCKERHUB_USERNAME}/uas-web-dinamis:latest
    container_name: app_web_dinamis
    ports:
      - "3000:80"
    restart: always
    # Tambahkan baris di bawah ini agar Apache PHP bisa membaca file .env server
    env_file:
      - .env

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: supersecretrootpassword
      MYSQL_DATABASE: uas_db
      MYSQL_USER: uas_user
      MYSQL_PASSWORD: uas_password_secure
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb_data: